/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Fabrica.Fabrica;
import dataTypes.DataProducto;
import dataTypes.DataRestaurante;
import entidades.Producto;
import interfaces.IControladorRestaurantes;
import java.awt.Component;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.Set;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fabian
 */
public class RegistrarProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
         
    Fabrica F = Fabrica.getInstance();
    IControladorRestaurantes cr  = F.getIControladorRestaurantes();
    DefaultTableModel TmodelI;
    BufferedImage imagenSeleccionada = null;
    private Component seleccionarImagen;
    String inputDialog;
    
    public RegistrarProducto() {
        initComponents();
        PromoFrame.setVisible(false);
        jButton2.setEnabled(false);
        jButton4.setEnabled(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          buttonGroup2 = new javax.swing.ButtonGroup();
          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          NombreProd = new javax.swing.JTextField();
          Descripcion = new javax.swing.JTextField();
          NombreResto = new javax.swing.JTextField();
          jButton1 = new javax.swing.JButton();
          jButton2 = new javax.swing.JButton();
          jLabel5 = new javax.swing.JLabel();
          jLabel6 = new javax.swing.JLabel();
          PromocionButton = new javax.swing.JRadioButton();
          IndividualButton = new javax.swing.JRadioButton();
          PromoFrame = new javax.swing.JInternalFrame();
          jButton4 = new javax.swing.JButton();
          jScrollPane1 = new javax.swing.JScrollPane();
          jTable1 = new javax.swing.JTable();
          jLabel7 = new javax.swing.JLabel();
          Descuento = new javax.swing.JTextField();
          jButton3 = new javax.swing.JButton();

          setClosable(true);
          setIconifiable(true);
          setMaximizable(true);
          setTitle("Registrar producto");
          setAutoscrolls(true);

          jLabel1.setText("Complete los siguientes campos:");

          jLabel3.setText("Descripcion:");

          jLabel4.setText("Restaurante:");

          NombreProd.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    NombreProdActionPerformed(evt);
               }
          });

          Descripcion.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    DescripcionActionPerformed(evt);
               }
          });

          NombreResto.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    NombreRestoActionPerformed(evt);
               }
          });

          jButton1.setText("Cancelar");
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });

          jButton2.setText("Registrar");
          jButton2.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
               }
          });

          jLabel6.setText("Nombre:");

          buttonGroup2.add(PromocionButton);
          PromocionButton.setText("Promocion");
          PromocionButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    PromocionButtonActionPerformed(evt);
               }
          });

          buttonGroup2.add(IndividualButton);
          IndividualButton.setText("Individual");
          IndividualButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    IndividualButtonActionPerformed(evt);
               }
          });

          PromoFrame.setTitle("Promocion");
          PromoFrame.setAutoscrolls(true);
          PromoFrame.setVisible(true);

          jButton4.setText("Aceptar");
          jButton4.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
               }
          });

          jTable1.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null},
                    {null, null},
                    {null, null},
                    {null, null},
                    {null, null}
               },
               new String [] {
                    "Producto", "Cantidad"
               }
          ));
          jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTable1MouseClicked(evt);
               }
          });
          jScrollPane1.setViewportView(jTable1);

          jLabel7.setText("Descuento porcentual:");

          Descuento.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    DescuentoActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout PromoFrameLayout = new javax.swing.GroupLayout(PromoFrame.getContentPane());
          PromoFrame.getContentPane().setLayout(PromoFrameLayout);
          PromoFrameLayout.setHorizontalGroup(
               PromoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(PromoFrameLayout.createSequentialGroup()
                    .addGroup(PromoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(PromoFrameLayout.createSequentialGroup()
                              .addContainerGap()
                              .addComponent(jScrollPane1))
                         .addGroup(PromoFrameLayout.createSequentialGroup()
                              .addGroup(PromoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(PromoFrameLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(PromoFrameLayout.createSequentialGroup()
                                        .addGap(221, 221, 221)
                                        .addComponent(jButton4)))
                              .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
          );
          PromoFrameLayout.setVerticalGroup(
               PromoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PromoFrameLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(PromoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel7)
                         .addComponent(Descuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButton4)
                    .addGap(19, 19, 19))
          );

          jButton3.setText("Seleccionar imagen");
          jButton3.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(67, 67, 67)
                              .addComponent(IndividualButton)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(PromocionButton)
                              .addGap(46, 46, 46))
                         .addGroup(layout.createSequentialGroup()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel6)
                                   .addComponent(jLabel3)
                                   .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                              .addGap(13, 13, 13)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(NombreProd, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                        .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                   .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(NombreResto, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(87, 87, 87))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PromoFrame)
                    .addContainerGap())
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jButton1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2)
                    .addGap(36, 36, 36))
               .addGroup(layout.createSequentialGroup()
                    .addGap(156, 156, 156)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jLabel1)
                    .addGap(32, 32, 32)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel6)
                         .addComponent(NombreProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel3)
                         .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel4)
                         .addComponent(NombreResto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(IndividualButton)
                         .addComponent(PromocionButton))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel2)
                         .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PromoFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3)
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jButton2)
                         .addComponent(jButton1))
                    .addGap(27, 27, 27))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

    private void NombreProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreProdActionPerformed

    private void DescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (PromocionButton.isSelected()){
            if (!cr.altaPromocion(NombreResto.getText(), NombreProd.getText(),Descripcion.getText(), Integer.parseInt(Descuento.getText()), 0, imagenSeleccionada)){
                for (int i = 0; i < jTable1.getRowCount();i++){
                    int Cantidad = (int) jTable1.getModel().getValueAt(i, 1);
                    if (Cantidad > 0){
                        boolean hayProductos = true;
                        DataProducto Producto = cr.seleccionarProducto((String)jTable1.getModel().getValueAt(i, 0),NombreResto.getText());
                        cr.seleccionarProducto(NombreProd.getText(),NombreResto.getText());
                        cr.agregarIndividualAPromocion(Producto.getNombre(),Cantidad);
                    }
                }
                JOptionPane.showMessageDialog(null, "El Producto ha sido registrado con exito");
            }
            else
                JOptionPane.showMessageDialog(null, "El Producto ingresado ya existe");
    }//GEN-LAST:event_jButton2ActionPerformed
        else {
        if (!cr.altaIndividual(NombreResto.getText(),NombreProd.getText(),Descripcion.getText(),Integer.parseInt(inputDialog),imagenSeleccionada)){
            JOptionPane.showMessageDialog(null, "El Producto ha sido registrado con exito");
        }
        else 
            JOptionPane.showMessageDialog(null, "El Producto ingresado ya existe");
        }
        dispose();
   }    
    private void PromocionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromocionButtonActionPerformed
            if ((!"".equals(NombreProd.getText())) && (!"".equals(Descripcion.getText()))) {
                if(cr.existeRestaurante(NombreResto.getText())){
                    cr.seleccionarRestaurante(NombreResto.getText());
                    DataRestaurante resto = cr.verInfoRestauranteM();
                    Set<DataProducto> productos =  resto.getProductos(3);
                    TmodelI = (DefaultTableModel) jTable1.getModel();
                    TmodelI.setRowCount(0);
                    for( DataProducto DI : productos){
                        if (DI.getTipo() == Producto.Individual) {
                        TmodelI.insertRow(TmodelI.getRowCount(), new Object[]{DI.getNombre(),0, 0});
                        }
                    }
                    PromoFrame.setVisible(true);
                }else JOptionPane.showMessageDialog(null, "El Nick del Restaurante no es valido");
            }else JOptionPane.showMessageDialog(null, "Ingrese Nombre y Descripcion del Producto");
    }//GEN-LAST:event_PromocionButtonActionPerformed

    private void IndividualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndividualButtonActionPerformed
        if ((!"".equals(NombreProd.getText())) && (!"".equals(Descripcion.getText()))) {
            if(cr.existeRestaurante(NombreResto.getText())){
                PromoFrame.setVisible(false);
                inputDialog = JOptionPane.showInputDialog(rootPane, "Ingrese el precio del producto", "Ingresar precio", JOptionPane.PLAIN_MESSAGE);            
                if(!inputDialog.equals(""))
                    jButton2.setEnabled(true);
            }else JOptionPane.showMessageDialog(null, "El Nick del Restaurante no es valido"); 
        }else JOptionPane.showMessageDialog(null, "Ingrese Nombre y Descripcion del Producto");
    }//GEN-LAST:event_IndividualButtonActionPerformed

    private void DescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescuentoActionPerformed
        if(!Descuento.getText().equals(""))
        jButton4.setEnabled(true);
    }//GEN-LAST:event_DescuentoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String cantProd = JOptionPane.showInputDialog(rootPane, "Ingrese la cantidad deseada", "Ingresar Cantidad", JOptionPane.PLAIN_MESSAGE);
        int row = jTable1.getSelectedRow();
        int cantVieja = (int) jTable1.getModel().getValueAt(row, 1);
        jTable1.getModel().setValueAt(Integer.parseInt(cantProd),row, 1);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showOpenDialog(seleccionarImagen);
        try {
            imagenSeleccionada = ImageIO.read(fileChooser.getSelectedFile());
        } catch (IOException ex) {
            imagenSeleccionada = null;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        PromoFrame.setVisible(false);
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void NombreRestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreRestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreRestoActionPerformed


     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JTextField Descripcion;
     private javax.swing.JTextField Descuento;
     private javax.swing.JRadioButton IndividualButton;
     private javax.swing.JTextField NombreProd;
     private javax.swing.JTextField NombreResto;
     private javax.swing.JInternalFrame PromoFrame;
     private javax.swing.JRadioButton PromocionButton;
     private javax.swing.ButtonGroup buttonGroup2;
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton2;
     private javax.swing.JButton jButton3;
     private javax.swing.JButton jButton4;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JTable jTable1;
     // End of variables declaration//GEN-END:variables
}
