/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Fabrica.Fabrica;
import dataTypes.DataProducto;
import dataTypes.DataRestaurante;
import entidades.Producto;
import interfaces.IControladorClientes;
import interfaces.IControladorRestaurantes;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fabian
 */
public class ActualizarProducto extends javax.swing.JInternalFrame {

     Fabrica F = Fabrica.getInstance();
     IControladorClientes cc = F.getIControladorClientes();
     IControladorRestaurantes cr = F.getIControladorRestaurantes();
     DefaultTableModel tabla;
     DataProducto dpActual;
     DataRestaurante drActual;

     public ActualizarProducto() {
          initComponents();

          tabla = (DefaultTableModel) tablaProds.getModel();
          tabla.setRowCount(0);
          Set<DataProducto> productos = cr.listarProductos();
          for (DataProducto dp : productos) {
               tabla.addRow(new Object[]{dp.getNombre(), dp.getNombreRes(), dp.getNickRes()});
          }

          textNombre.setEnabled(false);
          textDescripcion.setEnabled(false);
          textPrecio.setEnabled(false);
//          textImagen.setEnabled(false);
          textDescuento.setEnabled(false);
          textTipo.setEnabled(false);

          comboBoxAct.setEnabled(false);

     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProds = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textDescripcion = new javax.swing.JTextField();
        textDescuento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textPrecio = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textTipo = new javax.swing.JTextField();
        comboBoxAct = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Actualizar Producto");
        setAutoscrolls(true);

        tablaProds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Restaurante", "Nick Restaurante"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProdsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaProds);

        jLabel19.setText("Seleccione un producto:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del Producto:"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Nombre:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 65, -1, -1));

        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });
        jPanel2.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 65, 182, -1));

        jLabel7.setText("Descripcion:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 90, -1, -1));

        textDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDescripcionActionPerformed(evt);
            }
        });
        jPanel2.add(textDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 90, 182, -1));

        textDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDescuentoActionPerformed(evt);
            }
        });
        jPanel2.add(textDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 165, 182, -1));

        jLabel8.setText("Descuento:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 165, -1, -1));

        jLabel9.setText("Precio:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 140, -1, -1));

        jLabel11.setText("Activada:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 190, -1, -1));

        textPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrecioActionPerformed(evt);
            }
        });
        jPanel2.add(textPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 140, 182, -1));

        jLabel13.setText("Tipo:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 41, -1, -1));

        textTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTipoActionPerformed(evt);
            }
        });
        jPanel2.add(textTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 40, 182, -1));

        comboBoxAct.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Si" }));
        jPanel2.add(comboBoxAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 190, -1, -1));

        jButton6.setText("Cancelar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton6)
                        .addGap(175, 175, 175)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel19)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jButton3))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         dpActual = cr.seleccionarProducto((String) tablaProds.getValueAt(tablaProds.getSelectedRow(), 0),
                 (String) tablaProds.getValueAt(tablaProds.getSelectedRow(), 2));
         cr.seleccionarRestaurante(dpActual.getNickRes());
          
         if (!cr.existeProductoEnRestaurante(textNombre.getText()) || textNombre.getText().equals(dpActual.getNombre())) {
              if (dpActual.getTipo() == Producto.Individual) {
                   cr.actualizarIndividual(textNombre.getText(), textDescripcion.getText(),null /*textImagen.getText()*/,
                           Integer.parseInt(textPrecio.getText()));
              } else {
                   boolean v = comboBoxAct.getSelectedIndex() != 0;
                   cr.actualizarPromocion(textNombre.getText(), textDescripcion.getText(), null/*textImagen.getText()*/,
                           v, Integer.parseInt(textDescuento.getText()));
              }
              JOptionPane.showMessageDialog(null, "El producto ha sido actualizado con exito");
              tabla = (DefaultTableModel) tablaProds.getModel();
              tabla.setRowCount(0);
              Set<DataProducto> productos = cr.listarProductos();
              for (DataProducto dp : productos) {
                   tabla.addRow(new Object[]{dp.getNombre(), dp.getNombreRes(), dp.getNickRes()});
              }
              textDescuento.setText("");
//              textImagen.setText("");
              textDescripcion.setText("");
              textPrecio.setText("");
              textNombre.setText("");
              textTipo.setText("");
              comboBoxAct.setEnabled(false);
         } else {
              JOptionPane.showMessageDialog(null, "Ya existe un Producto con ese nombre en el Restaurante " + dpActual.getNombreRes());
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tablaProdsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProdsMouseClicked
         dpActual = cr.seleccionarProducto((String) tablaProds.getValueAt(tablaProds.getSelectedRow(), 0),
                 (String) tablaProds.getValueAt(tablaProds.getSelectedRow(), 2));

         if (dpActual.getTipo() == Producto.Individual) {
              textNombre.setEnabled(true);
              textDescripcion.setEnabled(true);
              textPrecio.setEnabled(true);
//              textImagen.setEnabled(true);
              textDescuento.setEnabled(false);
              comboBoxAct.setEnabled(false);

              textDescuento.setText("");
              textNombre.setText(dpActual.getNombre());
              textDescripcion.setText(dpActual.getDescripcion());
              textPrecio.setText(Integer.toString(dpActual.getPrecioUnitario()));
              textNombre.setText(dpActual.getNombre());
//              textImagen.setText(dpActual.getImagen());
              textTipo.setText("Individual");
         } else {
              textNombre.setEnabled(true);
              textDescripcion.setEnabled(true);
              textDescuento.setEnabled(true);
//              textImagen.setEnabled(true);
              textPrecio.setEnabled(false);
              comboBoxAct.setEnabled(true);

              if (dpActual.getAcivada()) {
                   comboBoxAct.setSelectedIndex(1);
              } else {
                   comboBoxAct.setSelectedIndex(0);
              }
              textPrecio.setText("");
              textNombre.setText(dpActual.getNombre());
              textDescripcion.setText(dpActual.getDescripcion());
              textDescuento.setText(Integer.toString(dpActual.getDescuento()));
              textNombre.setText(dpActual.getNombre());
              textTipo.setText("Promocion");
//              textImagen.setText(dpActual.getImagen());
         }
    }//GEN-LAST:event_tablaProdsMouseClicked

    private void textPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrecioActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_textPrecioActionPerformed

    private void textDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDescuentoActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_textDescuentoActionPerformed

    private void textDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDescripcionActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_textDescripcionActionPerformed

    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_textNombreActionPerformed

    private void textTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTipoActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_textTipoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboBoxAct;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaProds;
    private javax.swing.JTextField textDescripcion;
    private javax.swing.JTextField textDescuento;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPrecio;
    private javax.swing.JTextField textTipo;
    // End of variables declaration//GEN-END:variables
}
