/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Fabrica.Fabrica;
import interfaces.IControladorClientes;
import interfaces.IControladorPedidos;
import interfaces.IControladorRestaurantes;
import java.awt.Component;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabian
 */
public class RegistrarRestaurante extends javax.swing.JInternalFrame {
    Set<BufferedImage> imagenes = new HashSet<>();
    Fabrica F = Fabrica.getInstance();
    IControladorClientes cc  = F.getIControladorClientes();
    IControladorRestaurantes cr  = F.getIControladorRestaurantes();
    IControladorPedidos cp  = F.getIControladorPedidos();
    
    
    String imagenSeleccionada;
    private Component seleccionarImagen;
        
    public RegistrarRestaurante() {
        initComponents();
        lstCategorias.setModel(new DefaultListModel());
        lstImagenes.setModel(new DefaultListModel());
        ComboCat.removeAllItems();
        Set<String>  categorias = cr.listarCategorias();
        for (String cat : categorias){ 
            ComboCat.addItem(cat);
        }      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        RestoNick = new javax.swing.JTextField();
        ComboCat = new javax.swing.JComboBox();
        RestoContra = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        RestoNom = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        RestoDir = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCategorias = new javax.swing.JList();
        btnAgregarCat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstImagenes = new javax.swing.JList();
        RestoMail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registro Restaurante");
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(456, 490));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Contraseña");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel11.setText("Nombre:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel12.setText("Direccion:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel13.setText("Complete los siguientes campos:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, -1));

        RestoNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestoNickActionPerformed(evt);
            }
        });
        getContentPane().add(RestoNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 224, -1));

        ComboCat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboCatItemStateChanged(evt);
            }
        });
        ComboCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCatActionPerformed(evt);
            }
        });
        getContentPane().add(ComboCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 160, -1));

        RestoContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestoContraActionPerformed(evt);
            }
        });
        getContentPane().add(RestoContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 224, -1));

        jLabel14.setText("Selecciona al menos una de las siguientes categorias:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 340, -1));
        getContentPane().add(RestoNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 224, -1));

        jButton3.setText("Agregar Imagen...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 140, -1));

        RestoDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestoDirActionPerformed(evt);
            }
        });
        getContentPane().add(RestoDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 224, -1));

        jLabel9.setText("NickName:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jScrollPane1.setViewportView(lstCategorias);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 160, -1));

        btnAgregarCat.setText("Agregar Categoría");
        btnAgregarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCatActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 160, -1));

        jScrollPane2.setViewportView(lstImagenes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 210, -1));
        getContentPane().add(RestoMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 224, -1));

        jLabel15.setText("Email:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if(!RestoNick.getText().equals("") && !RestoContra.getText().equals("") && !RestoDir.getText().equals("") && 
            !RestoNom.getText().equals("")){
            
            if(lstCategorias.getModel().getSize() != 0){
                if (!cr.altaRestaurante( RestoNick.getText(),RestoMail.getText() , RestoContra.getText(), RestoNom.getText() ,RestoDir.getText() , imagenes)){
                   DefaultListModel lm = (DefaultListModel) lstCategorias.getModel();
                   for (int i = 0; i< lm.getSize(); i++ )
                   {

                      cr.seleccionarCategoria(lm.getElementAt(i).toString());
                         cr.agregarCategoriasARestaurante();
                   }
                   JOptionPane.showMessageDialog(null, "El restaurante ha sido registrado con éxito");
                   dispose();
                }
                else
                JOptionPane.showMessageDialog(null, "EL restaurante que ingresó ya existe, intentelo de nuevo");
            }else
                JOptionPane.showMessageDialog(null, "Debe seleccionar por lo menos una Categoría");
        }
        else
            JOptionPane.showMessageDialog(null, "Información incompleta");
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void RestoNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestoNickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RestoNickActionPerformed

    private void ComboCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCatActionPerformed
       
    }//GEN-LAST:event_ComboCatActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setMultiSelectionEnabled(true);
        int seleccion = fileChooser.showOpenDialog(seleccionarImagen);
        if(seleccion==JFileChooser.APPROVE_OPTION){
            File[] files = fileChooser.getSelectedFiles();
            DefaultListModel lm = (DefaultListModel) lstImagenes.getModel();
            for (File file : files) {
                try {
                    imagenes.add(ImageIO.read(file));
                }catch (IOException ex) {
                    Logger.getLogger(RegistrarRestaurante.class.getName()).log(Level.SEVERE, null, ex);
                }
                lm.addElement(file.getAbsolutePath());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void RestoDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestoDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RestoDirActionPerformed

    private void ComboCatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboCatItemStateChanged
         
      
    }//GEN-LAST:event_ComboCatItemStateChanged

    private void btnAgregarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCatActionPerformed
        
        DefaultListModel lm = (DefaultListModel) lstCategorias.getModel();
        DefaultComboBoxModel cm = (DefaultComboBoxModel) ComboCat.getModel();
        
        lm.addElement(cm.getSelectedItem());
    }//GEN-LAST:event_btnAgregarCatActionPerformed

    private void RestoContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestoContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RestoContraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboCat;
    private javax.swing.JTextField RestoContra;
    private javax.swing.JTextField RestoDir;
    private javax.swing.JTextField RestoMail;
    private javax.swing.JTextField RestoNick;
    private javax.swing.JTextField RestoNom;
    private javax.swing.JButton btnAgregarCat;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstCategorias;
    private javax.swing.JList lstImagenes;
    // End of variables declaration//GEN-END:variables
}
