/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Fabrica.Fabrica;
import dataTypes.DataProducto;
import dataTypes.DataRestaurante;
import interfaces.IControladorRestaurantes;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Fede
 */
public class VerInfoRestaurante extends javax.swing.JInternalFrame {

     String[] imagenes;
     int imgActual = 0;
     Fabrica f = Fabrica.getInstance();
     IControladorRestaurantes cr = f.getIControladorRestaurantes();

     /**
      * Creates new form VerInfoRestaurante
      */
     public VerInfoRestaurante() {
          initComponents();
          LlenarTreeRestaurantes();
          //frmInfoRestaurante.setVisible(false);
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        txtDireccion = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        btnSigImagen = new javax.swing.JButton();
        btnAntImagen = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNick = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        setTitle("Ver Información de Restaurante");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Restaurantes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Categorías");
        jTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreeMouseClicked(evt);
            }
        });
        jTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jTree);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 330, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 460));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del Restaurante"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Nombre", "Descripción", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 460, 210));

        txtDireccion.setEditable(false);
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 170, -1));

        txtEmail.setEditable(false);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 95, 170, -1));

        txtNombre.setEditable(false);
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 170, -1));

        jLabel8.setText("Dirección:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabel7.setText("Correo Electrónico:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 95, -1, -1));

        jLabel3.setText("Nombre:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        lblImagen.setBackground(new java.awt.Color(204, 204, 204));
        lblImagen.setIconTextGap(0);
        lblImagen.setOpaque(true);
        jPanel2.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 120));

        btnSigImagen.setText(">");
        btnSigImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigImagenActionPerformed(evt);
            }
        });
        jPanel2.add(btnSigImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 50, -1));

        btnAntImagen.setText("<");
        btnAntImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntImagenActionPerformed(evt);
            }
        });
        jPanel2.add(btnAntImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 50, -1));

        jLabel5.setText("Productos:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        txtNick.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 230, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 480, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void LlenarDatosRestaurante() {
          DataRestaurante dr = cr.verInfoRestauranteM();

          txtNick.setText(dr.getNick());
          txtNombre.setText(dr.getNombre());
          txtDireccion.setText(dr.getDireccion());
          txtEmail.setText(dr.getMail());

          if (dr.getImagenes().size() > 0) {
               imgActual = 0;
               imagenes = new String[dr.getImagenes().size()];
               Iterator<String> iti = dr.getImagenes().iterator();
               int i = 0;
               while (iti.hasNext()) {
                    imagenes[i] = iti.next();
                    i++;
               }
               try {

                    BufferedImage img = ImageIO.read(new File(imagenes[0]));
                    lblImagen.setIcon(new ImageIcon(img.getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_SMOOTH)));
               } catch (IOException e) {
                    e.getMessage();
               }
          } else {
               imagenes = null;
               lblImagen.setIcon(null);
          }

          Set<DataProducto> productos = dr.getProductos();

          DefaultTableModel tm = (DefaultTableModel) tblProductos.getModel();
          tm.setRowCount(0);

          Iterator<DataProducto> it = productos.iterator();
          while (it.hasNext()) {
               DataProducto dprod = it.next();
               String tipo;
               if (dprod.getTipo() == 0) {
                    tipo = "Individual";
               } else {
                    tipo = "Promoción";
               }
               tm.addRow(new Object[]{tipo, dprod.getNombre(), dprod.getDescripcion(), dprod.getPrecioUnitario()});
          }

     }

     private void LlenarTreeRestaurantes() {

          DefaultTreeModel tm = (DefaultTreeModel) jTree.getModel();
          DefaultMutableTreeNode root = (DefaultMutableTreeNode) tm.getRoot();
          Set<String> cats = cr.listarCategorias();
          Iterator<String> itc = cats.iterator();
          while (itc.hasNext()) {
               String cat = itc.next();
               DefaultMutableTreeNode tCat = new DefaultMutableTreeNode(cat);
               root.add(tCat);

               cr.seleccionarCategoria(cat);
               Set<DataRestaurante> restaurantes = cr.listarRestaurantesCategoria();
               Iterator<DataRestaurante> itr = restaurantes.iterator();
               while (itr.hasNext()) {
                    DefaultMutableTreeNode tRest = new DefaultMutableTreeNode(itr.next());

                    tCat.add(tRest);

               }

          }
     }


    private void jTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreeMouseClicked

    }//GEN-LAST:event_jTreeMouseClicked

    private void jTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeValueChanged
         DefaultMutableTreeNode t = (DefaultMutableTreeNode) jTree.getLastSelectedPathComponent();

         if (t.getLevel() == 2) {

              DataRestaurante dr = ((DataRestaurante) t.getUserObject());
              cr.seleccionarRestaurante(dr.getNick());
            // frmInfoRestaurante.show();
              //frmSeleccionarRestaurante.dispose();
              LlenarDatosRestaurante();
         }
    }//GEN-LAST:event_jTreeValueChanged

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed

    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnSigImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigImagenActionPerformed
         if (imagenes != null) {
              if (imgActual < imagenes.length - 1) {
                   imgActual++;
              }
              try {

                   BufferedImage img = ImageIO.read(new File(imagenes[imgActual]));
                   lblImagen.setIcon(new ImageIcon(img.getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_SMOOTH)));
              } catch (IOException e) {
                   e.getMessage();
              }
         }
    }//GEN-LAST:event_btnSigImagenActionPerformed

    private void btnAntImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntImagenActionPerformed
         if (imagenes != null) {
              if (imgActual > 0) {
                   imgActual--;
                   try {

                        BufferedImage img = ImageIO.read(new File(imagenes[imgActual]));
                        lblImagen.setIcon(new ImageIcon(img.getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_SMOOTH)));
                   } catch (IOException e) {
                        e.getMessage();
                   }
              }
         }
    }//GEN-LAST:event_btnAntImagenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAntImagen;
    private javax.swing.JButton btnSigImagen;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTree jTree;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel txtNick;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
