/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;
import publicar.DataPedido;
import publicar.PublicadorMovil;
import publicar.PublicadorMovilService;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import publicar.Estado;

/**
 *
 * @author ut603269
 */
public class ActualizarEstadoPedido extends javax.swing.JInternalFrame {

    PublicadorMovilService service;
    PublicadorMovil port;
    ButtonGroup bg;
    int pedidoSeleccionado;

    /**
     * Creates new form VerPedido
     */
    public ActualizarEstadoPedido() {
        try{
            service = new PublicadorMovilService(Main.cargarURL());
            port = service.getPublicadorMovilPort();
        }catch(Exception e){
            System.err.printf(e.getMessage());
        }
        
        
        initComponents();
        bg = new ButtonGroup();
        bg.add(rbtPreparacion);
        bg.add(rbtEnviado);
        bg.add(rbtRecibido);
        LlenarTablaPedidos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbtEnviado = new javax.swing.JRadioButton();
        rbtRecibido = new javax.swing.JRadioButton();
        btnActualizar = new javax.swing.JButton();
        rbtPreparacion = new javax.swing.JRadioButton();

        setTitle("Actualizar Estado");
        setPreferredSize(new java.awt.Dimension(321, 480));

        jLabel1.setText("Seleccione un pedido:");

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Estado", "Cliente", "Fecha"
            }
        ));
        tblPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPedidos);
        if (tblPedidos.getColumnModel().getColumnCount() > 0) {
            tblPedidos.getColumnModel().getColumn(0).setMinWidth(30);
            tblPedidos.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblPedidos.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        rbtEnviado.setText("Enviado");
        rbtEnviado.setEnabled(false);
        rbtEnviado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEnviadoActionPerformed(evt);
            }
        });

        rbtRecibido.setText("Recibido");
        rbtRecibido.setEnabled(false);
        rbtRecibido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtRecibidoActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar Estado");
        btnActualizar.setEnabled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        rbtPreparacion.setText("Preparación");
        rbtPreparacion.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtPreparacion)
                    .addComponent(rbtRecibido)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtEnviado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtPreparacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtEnviado)
                    .addComponent(btnActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtRecibido)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JDesktopPane esc = (JDesktopPane) this.getParent();
        this.dispose();
        Menu men = new Menu();
        esc.add(men);
        men.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidosMouseClicked
        DefaultTableModel tablaP = (DefaultTableModel) tblPedidos.getModel();
        String estado = (tablaP.getValueAt(tblPedidos.getSelectedRow(), 1)).toString();
        pedidoSeleccionado = (int) (tablaP.getValueAt(tblPedidos.getSelectedRow(), 0));
        switch (estado) {
            case "PREPARACION":
                rbtPreparacion.setSelected(true);
                rbtPreparacion.setEnabled(false);
                rbtEnviado.setEnabled(true);
                rbtRecibido.setEnabled(true);
                btnActualizar.setEnabled(false);
                break;
            case "ENVIADO":
                rbtEnviado.setSelected(true);
                rbtPreparacion.setEnabled(false);
                rbtEnviado.setEnabled(false);
                rbtRecibido.setEnabled(true);
                btnActualizar.setEnabled(false);
                break;
            default:
                rbtRecibido.setSelected(true);
                rbtPreparacion.setEnabled(false);
                rbtEnviado.setEnabled(false);
                rbtRecibido.setEnabled(false);
                btnActualizar.setEnabled(false);
                break;
        }


    }//GEN-LAST:event_tblPedidosMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        Estado e;
        if (bg.getSelection().isEnabled()) {
            if (bg.getSelection().equals(rbtRecibido.getModel())) {
                e = Estado.RECIBIDO;
            } else if (bg.getSelection().equals(rbtEnviado.getModel())) {
                e = Estado.ENVIADO;
            } else {
                e = Estado.PREPARACION;
            }

            port.actualizarEstadoPedido(pedidoSeleccionado, e, null);
            JOptionPane.showMessageDialog(null, "El estado del pedido ha sido actualizado con éxito.");
            btnActualizar.setEnabled(false);
            bg.clearSelection();
            rbtPreparacion.setEnabled(false);
            rbtEnviado.setEnabled(false);
            rbtRecibido.setEnabled(false);
            LlenarTablaPedidos();
        }


    }//GEN-LAST:event_btnActualizarActionPerformed

    private void rbtRecibidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtRecibidoActionPerformed
        btnActualizar.setEnabled(true);
    }//GEN-LAST:event_rbtRecibidoActionPerformed

    private void rbtEnviadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEnviadoActionPerformed
        btnActualizar.setEnabled(true);
    }//GEN-LAST:event_rbtEnviadoActionPerformed
    private void LlenarTablaPedidos() {
        DefaultTableModel tablaP = (DefaultTableModel) tblPedidos.getModel();
        tablaP.setRowCount(0);
        try{
            List<DataPedido> pedidos = port.getPedidos().getItem();

            for (DataPedido dp : pedidos) {

                String fecha = dp.getFecha().getDia() + "/" + dp.getFecha().getMes() + "/" + dp.getFecha().getAnio();
                if (dp.getFecha().getHora() != -1) {
                    fecha = fecha + "-" + dp.getFecha().getHora() + ":" + dp.getFecha().getMinuto();
                }
                tablaP.addRow(new Object[]{dp.getIdP(), dp.getEstado().toString(), dp.getNickCli(), fecha});
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Sin conexion");
        }    
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtEnviado;
    private javax.swing.JRadioButton rbtPreparacion;
    private javax.swing.JRadioButton rbtRecibido;
    private javax.swing.JTable tblPedidos;
    // End of variables declaration//GEN-END:variables
}
